name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  flatpak:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Update package lists
      run: sudo apt-get update
  
    - name: Install build tools
      run: sudo apt-get install meson git gettext flatpak flatpak-builder

    - name: Install build dependencies
      run: |
        sudo apt-get install libadwaita-1-dev libgpgme-dev
        flatpak remote-add --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo
        flatpak install --user --assumeyes org.gnome.Sdk//47 org.gnome.Platform//47

    - name: Build development profile
      run: flatpak-builder --user --install --install-deps-from=flathub --force-clean _meson com.konstantintutsch.Lock.Devel.yaml
